modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/bl4ckscor3/LocateBiome/issues"
displayURL="http://minecraft.curseforge.com/projects/locatebiome"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="locatebiome" #mandatory
version="v1.0" #mandatory
displayName="LocateBiome" #mandatory
description='''Adds the /locatebiome command from 1.16 snapshots into earlier versions!''' #mandatory

[[dependencies.locatebiome]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.locatebiome]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"